services:
    dev:
        build:
            context: .
            target: dev
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 5173:5173
        # develop:
        #   watch:
        #     - action: sync
        #       path: ./src
        #       target: /app/src
        #       ignore:
        #         - node_modules/
        #     - action: rebuild
        #       path: pacakage.json
        tty: true

    prod:
        build:
            context: .
            target: prod
        volumes:
            - ./dist:/usr/share/nginx/html
        ports:
            - 80:80