name: update-data
env:
    GITHUB_USERNAME: ${{ github.repository_owner }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    MEDIUM_USERNAME: xuzhusheng
on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"
jobs:
    update-data:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      package.json
                      package-lock.json
                      fetch.js
                  sparse-checkout-cone-mode: false
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm i -D @swc/cli @swc/core
            - run: npm ci
            - run: |
                  node fetch.js
                  pwd
                  ls
            - run: |
                  git add ./public/profile.json ./public/blogs.json
                  git commit -m "update data"
                  git push -u origin master
