name: update-data
env:
    GITHUB_USERNAME: ${{ github.repository_owner }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    MEDIUM_USERNAME: xuzhusheng
on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      fetch.js
                  sparse-checkout-cone-mode: false
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: node fetch.js
            - run: |
                  git add ./public/profile.json ./public/blogs.json
                  git commit -m "update data"
                  git push -u origin master
